server:
  port: 8001

spring:
  profiles:
    active: dev #多環境配置dev/prod，不寫就是默認default值

  datasource:
    url: jdbc:mysql://localhost:3306/db2024?serverTimezone=Asia/Taipei
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    
# zipkin
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 #採樣率默認為0.1(0.1就是10次只能有一次被記錄下來)，值越大收集越即時。